// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: base.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum Hazkey_StatusCode: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecified // = 0
  case success // = 1
  case failed // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .success
    case 2: self = .failed
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .success: return 1
    case .failed: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Hazkey_StatusCode] = [
    .unspecified,
    .success,
    .failed,
  ]

}

struct Hazkey_RequestEnvelope: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var payload: Hazkey_RequestEnvelope.OneOf_Payload? = nil

  var keyEvent: Hazkey_Commands_KeyEvent {
    get {
      if case .keyEvent(let v)? = payload {return v}
      return Hazkey_Commands_KeyEvent()
    }
    set {payload = .keyEvent(newValue)}
  }

  /// hazkey.commands.NewComposingText new_composing_text = 1;
  /// hazkey.commands.SetContext set_context = 2;
  /// hazkey.commands.InputChar input_char = 3;
  /// hazkey.commands.ModifierEvent modifier_event = 4;
  /// hazkey.commands.MoveCursor move_cursor = 5;
  /// hazkey.commands.PrefixComplete prefix_complete = 6;
  /// hazkey.commands.DeleteLeft delete_left = 7;
  /// hazkey.commands.DeleteRight delete_right = 8;
  /// hazkey.commands.GetComposingString get_composing_string = 9;
  /// hazkey.commands.GetHiraganaWithCursor get_hiragana_with_cursor = 10;
  /// hazkey.commands.GetCandidates get_candidates = 11;
  /// hazkey.commands.GetCurrentInputModeInfo get_current_input_mode = 12;
  var saveLearningData: Hazkey_Commands_SaveLearningData {
    get {
      if case .saveLearningData(let v)? = payload {return v}
      return Hazkey_Commands_SaveLearningData()
    }
    set {payload = .saveLearningData(newValue)}
  }

  var resetState: Hazkey_Commands_ResetState {
    get {
      if case .resetState(let v)? = payload {return v}
      return Hazkey_Commands_ResetState()
    }
    set {payload = .resetState(newValue)}
  }

  var getConfig: Hazkey_Config_GetConfig {
    get {
      if case .getConfig(let v)? = payload {return v}
      return Hazkey_Config_GetConfig()
    }
    set {payload = .getConfig(newValue)}
  }

  var setConfig: Hazkey_Config_SetConfig {
    get {
      if case .setConfig(let v)? = payload {return v}
      return Hazkey_Config_SetConfig()
    }
    set {payload = .setConfig(newValue)}
  }

  var getDefaultProfile: Hazkey_Config_GetDefaultProfile {
    get {
      if case .getDefaultProfile(let v)? = payload {return v}
      return Hazkey_Config_GetDefaultProfile()
    }
    set {payload = .getDefaultProfile(newValue)}
  }

  var clearAllHistory_p: Hazkey_Config_ClearAllHistory {
    get {
      if case .clearAllHistory_p(let v)? = payload {return v}
      return Hazkey_Config_ClearAllHistory()
    }
    set {payload = .clearAllHistory_p(newValue)}
  }

  var reloadZenzaiModel: Hazkey_Config_ReloadZenzaiModel {
    get {
      if case .reloadZenzaiModel(let v)? = payload {return v}
      return Hazkey_Config_ReloadZenzaiModel()
    }
    set {payload = .reloadZenzaiModel(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Payload: Equatable, Sendable {
    case keyEvent(Hazkey_Commands_KeyEvent)
    /// hazkey.commands.NewComposingText new_composing_text = 1;
    /// hazkey.commands.SetContext set_context = 2;
    /// hazkey.commands.InputChar input_char = 3;
    /// hazkey.commands.ModifierEvent modifier_event = 4;
    /// hazkey.commands.MoveCursor move_cursor = 5;
    /// hazkey.commands.PrefixComplete prefix_complete = 6;
    /// hazkey.commands.DeleteLeft delete_left = 7;
    /// hazkey.commands.DeleteRight delete_right = 8;
    /// hazkey.commands.GetComposingString get_composing_string = 9;
    /// hazkey.commands.GetHiraganaWithCursor get_hiragana_with_cursor = 10;
    /// hazkey.commands.GetCandidates get_candidates = 11;
    /// hazkey.commands.GetCurrentInputModeInfo get_current_input_mode = 12;
    case saveLearningData(Hazkey_Commands_SaveLearningData)
    case resetState(Hazkey_Commands_ResetState)
    case getConfig(Hazkey_Config_GetConfig)
    case setConfig(Hazkey_Config_SetConfig)
    case getDefaultProfile(Hazkey_Config_GetDefaultProfile)
    case clearAllHistory_p(Hazkey_Config_ClearAllHistory)
    case reloadZenzaiModel(Hazkey_Config_ReloadZenzaiModel)

  }

  init() {}
}

struct Hazkey_ResponseEnvelope: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var status: Hazkey_StatusCode = .unspecified

  var errorMessage: String = String()

  var payload: Hazkey_ResponseEnvelope.OneOf_Payload? = nil

  var text: String {
    get {
      if case .text(let v)? = payload {return v}
      return String()
    }
    set {payload = .text(newValue)}
  }

  /// hazkey.commands.CandidatesResult candidates = 4;
  /// hazkey.commands.TextWithCursor text_with_cursor = 5;
  /// hazkey.commands.CurrentInputModeInfo current_input_mode_info = 6;
  var clientState: Hazkey_Commands_ClientState {
    get {
      if case .clientState(let v)? = payload {return v}
      return Hazkey_Commands_ClientState()
    }
    set {payload = .clientState(newValue)}
  }

  var currentConfig: Hazkey_Config_CurrentConfig {
    get {
      if case .currentConfig(let v)? = payload {return v}
      return Hazkey_Config_CurrentConfig()
    }
    set {payload = .currentConfig(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Payload: Equatable, Sendable {
    case text(String)
    /// hazkey.commands.CandidatesResult candidates = 4;
    /// hazkey.commands.TextWithCursor text_with_cursor = 5;
    /// hazkey.commands.CurrentInputModeInfo current_input_mode_info = 6;
    case clientState(Hazkey_Commands_ClientState)
    case currentConfig(Hazkey_Config_CurrentConfig)

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "hazkey"

extension Hazkey_StatusCode: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNSPECIFIED"),
    1: .same(proto: "SUCCESS"),
    2: .same(proto: "FAILED"),
  ]
}

extension Hazkey_RequestEnvelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RequestEnvelope"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "key_event"),
    13: .standard(proto: "save_learning_data"),
    14: .standard(proto: "reset_state"),
    100: .standard(proto: "get_config"),
    101: .standard(proto: "set_config"),
    102: .standard(proto: "get_default_profile"),
    103: .standard(proto: "clear_all_history"),
    104: .standard(proto: "reload_zenzai_model"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Hazkey_Commands_KeyEvent?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .keyEvent(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .keyEvent(v)
        }
      }()
      case 13: try {
        var v: Hazkey_Commands_SaveLearningData?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .saveLearningData(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .saveLearningData(v)
        }
      }()
      case 14: try {
        var v: Hazkey_Commands_ResetState?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .resetState(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .resetState(v)
        }
      }()
      case 100: try {
        var v: Hazkey_Config_GetConfig?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .getConfig(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .getConfig(v)
        }
      }()
      case 101: try {
        var v: Hazkey_Config_SetConfig?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .setConfig(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .setConfig(v)
        }
      }()
      case 102: try {
        var v: Hazkey_Config_GetDefaultProfile?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .getDefaultProfile(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .getDefaultProfile(v)
        }
      }()
      case 103: try {
        var v: Hazkey_Config_ClearAllHistory?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .clearAllHistory_p(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .clearAllHistory_p(v)
        }
      }()
      case 104: try {
        var v: Hazkey_Config_ReloadZenzaiModel?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .reloadZenzaiModel(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .reloadZenzaiModel(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.payload {
    case .keyEvent?: try {
      guard case .keyEvent(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .saveLearningData?: try {
      guard case .saveLearningData(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
    }()
    case .resetState?: try {
      guard case .resetState(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
    }()
    case .getConfig?: try {
      guard case .getConfig(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 100)
    }()
    case .setConfig?: try {
      guard case .setConfig(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 101)
    }()
    case .getDefaultProfile?: try {
      guard case .getDefaultProfile(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 102)
    }()
    case .clearAllHistory_p?: try {
      guard case .clearAllHistory_p(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 103)
    }()
    case .reloadZenzaiModel?: try {
      guard case .reloadZenzaiModel(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 104)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_RequestEnvelope, rhs: Hazkey_RequestEnvelope) -> Bool {
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Hazkey_ResponseEnvelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ResponseEnvelope"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "status"),
    2: .standard(proto: "error_message"),
    3: .same(proto: "text"),
    4: .standard(proto: "client_state"),
    100: .standard(proto: "current_config"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.errorMessage) }()
      case 3: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.payload != nil {try decoder.handleConflictingOneOf()}
          self.payload = .text(v)
        }
      }()
      case 4: try {
        var v: Hazkey_Commands_ClientState?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .clientState(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .clientState(v)
        }
      }()
      case 100: try {
        var v: Hazkey_Config_CurrentConfig?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .currentConfig(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .currentConfig(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.status != .unspecified {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 1)
    }
    if !self.errorMessage.isEmpty {
      try visitor.visitSingularStringField(value: self.errorMessage, fieldNumber: 2)
    }
    switch self.payload {
    case .text?: try {
      guard case .text(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    }()
    case .clientState?: try {
      guard case .clientState(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .currentConfig?: try {
      guard case .currentConfig(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 100)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_ResponseEnvelope, rhs: Hazkey_ResponseEnvelope) -> Bool {
    if lhs.status != rhs.status {return false}
    if lhs.errorMessage != rhs.errorMessage {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
